### ISSUE TITLE
Kenny Hammerlund - Unit/Snap Testing || devOps - Javascript 

### ISSUE THREAD

**Issue by KennyHammerlund** [NotMyself/pair-with-me#1]
Follow this template in your Issue title: `Bobby Johnson - Dependency Injection - C# .net core`

## Describe your level of experience with software development.
I have been a professional developer for a year now. I graduated from metro state with a BS  in computer information technology. I have a contract with American Poolplayers Association working as a remote full stack dev. 
 
## Describe what you would like to learn.
I would like to know more about testing. We just started to build a React Native app and as a company we have no automated testing as of now. I have been branching out to learn more about testing. Most of my experience has been focused towards Jest and snapshot testing but I am interested in learning more.

I would also be interested in learning more about devOps. I have set up a few projects and deployed to AWS EC2, Lightsail and S3 but EB is still a mystery. I would also like to know about scaling web applications. 
  
## Describe what you would like to teach.
I can offer quite a bit of information regarding GraphQL and its Javascript implementation. Our GQL api has been in production for 18 months now and I have built quite a bit of it over the past year. 

## When would you be available to stream?
Most anytime besides Wednesday/Thursdays before 4. 

## Prerequisites

Check all the boxes that apply to you:

- [X] I have [zoom](https://zoom.us/) installed.
- [X] I have a microphone capable of recording my voice.
- [X] I have a camera of some type capable of recording myself from the shoulders up.
- [X] I have Visual Studio Code installed on my development machine.
- [X] I have the [Live Share](https://marketplace.visualstudio.com/items?itemName=MS-vsliveshare.vsliveshare) extension installed and configured in Visual Studio Code.
- [X] I understand that I will be asked to do a preflight check prior to being scheduled.

**Comment by NotMyself** [comment]
Hey Kenny! Thanks for signing up to be on my stream. I like the topics you suggested they sound fun. I will email you some details on how to arrange a time to schedule our quick meeting. Check your email on the account listed here on github.
